const projectsList = [
  {
    image: "https://source.unsplash.com/250x200/?project",
    tag: ["html", "css", "responsive"],
    title: "Recipe Blog",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?construction",
    tag: ["html", "css", "responsive"],
    title: "My Gallary",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?power",
    tag: ["html", "css", "responsive"],
    title: "Checkout",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?god",
    tag: ["html", "css"],
    title: "portfolio",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?future",
    tag: ["html" ],
    title: "Nature Spirit",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?hacker",
    tag: ["html", "css", ],
    title: "Supernatural",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?technology",
    tag: [ "responsive"],
    title: "Interactiva",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?spirit",
    tag: ["html"],
    title: "Ranger",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?car",
    tag: ["html", "css", "responsive"],
    title: "Ghosts",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?house",
    tag: ["html",  "responsive"],
    title: "Aura",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?girl",
    tag: ["html", "css", "responsive"],
    title: "God of War",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?boy",
    tag: ["html", "css", "responsive"],
    title: "Jungle Fury",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?plane",
    tag: ["html",  "responsive"],
    title: "Wakanda",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?paper",
    tag: ["html", "css", "responsive"],
    title: "Neumorphic",
    des: "",
    demo: "",
    code: "",
  },
  {
    image: "https://source.unsplash.com/250x200/?cartoon",
    tag: ["html", "css", "responsive"],
    title: "Glassmorphic",
    des: "",
    demo: "",
    code: "",
  }
];


export default projectsList;